import React from "react"


function Articles(props) {
    return (
        <div>
            <h1>Object-Oriented Ontology in Archaeology</h1>
        
    <div className="scrollBox">
        <p>
            <b>Introduction</b>
            <br></br>
            <br></br>
            The “Anthropocene,” or the geological epoch in which humans are the main influencers of the environment, has had a profound effect on social theory, leading many to reevaluate the “nature/culture” divide of Western philosophy and approach human-environmental relationships in novel ways. Authors such as Anna Tsing (2005; 2015; 2017), Donna Haraway (2008; 2016), John Hartigan (2015; 2017), Eduardo Kohn (2015; 2017; 2013), and, as of late, Bruno Latour (2013; 2017), have invited us to view ecological communities as a multiplicity of actors who produce and reproduce ecological communities through “fleshy” entanglements. The “human” is no longer the sole arbiter of thought or the mediator of what we call the “social,” within such “post-human” ontologies. Rather, soils, plants, animals, fungi, insects, climates, glaciers and other entities, are equal actors who are capable of mutually influencing one another.
                    This attention to “more than human world systems” has taken root in archaeology through the so called “new materialism” as advocated by Gavin Lucas (2005; 2012), Brian Boyd (2017), Bjornar Olsen (2012), Nick Overton (2016; 2013), and most famously Ian Hodder (2012) with his book Entangled. Simplified, these archaeologists acknowledge the agency of non-human actors and argue for archaeological interpretations which examine the connection between people, things, and non-human life. But how “new” is the “ontological turn” and should all archaeologists take it seriously?
                    Here, I examine the foundations of the “new materialism” and argue against its application by those working in contexts of settler-colonialism. I show how non-human agency, the main tenet of the “ontological turn,” has a deep history in indigenous ontologies and argue that rejecting indigenous epistemologies in favor of western philosophy when describing human-non-human relations is a form of academic colonialism. I then advocate for an approach based on the paradigm of historical-ecological which I find more attune to place based histories, localized forms of knowledge, and object entanglements that the “ontological shift” strives for.
                    Anthropology’s “ontological shift” and its philosophical foundations
                    Within the last two decades, the so called “ontological turn” has called for a decentering of the human subject and an opening up of ethnography to non-human entities in an effort to “transcend” modernist divisions between “nature” and “culture.” (Bessire and Bond 2014; de Castro 2015; Ginn 2014; Haraway 2008; 2016; Kohn 2013; Tsing 2015; 2017). This “shift” has taken different forms and is known by different names, including “post-humanism,” (Hayles 1999) “non-modernism,”(Latour 1993; 2013) and “more than human world systems” (Tsing 2005). These approaches are united in their attention to non-human agency and the role of non-human entities in the co-production of historical/social/ecological worlds. Some have even attempted to examine the sociality objects in the absence of humans, bordering on an “ethnography of things” (Giaccardi, et al. 2016).
                    Many whose work can be considered part of this “ontological turn” draw upon “object-oriented ontology” (OOO), either implicitly or explicitly. OOO is a recent philosophical trend which borrows heavily from Heidegger’s (2010) phenomenology and more recently Latour’s (2013) insights into a “flat-ontology.” In this section, I will first detail what object-oriented ontology is and then examine its use, and question its usefulness, in archaeology.
                    <br></br>
                    <br></br>
                    <b>Object-oriented ontology</b>
                    <br></br>
                    Object-oriented ontology (OOO) emerged in the late 1990s as “object-oriented philosophy” in Graham Harman’s (1999) Ph.D. dissertation titled “Tool-Being: Elements in a Theory of Objects.” Harman’s recent books on the subject (2010; 2011; 2018a) and one forthcoming (2018b) attest to the growing popularity of this branch of philosophy and to Harman’s authority in the field. I draw primarily on his work in making sense of OOO and how it relates to the “ontological shift.”
                    For Harman (2018a), OOO is as a form of “speculative realism,” a term that describes a philosophy that lies between a staunch materialism, which he calls “smallism” (30) and a hyper-relativism, or “constructionism ” (9). He argues that both “smallism” and “constructionism” deny the validity of objects as “things-in-themselves,” a term borrowed from Kant, or entities that cannot be reduced to the sum of their parts or valued simply by their relations with other objects. Importantly, Harman argues that OOO is not a form of “materialism” (258) as an “object” need not be material but only irreducible and exist independently of its relations, thus allowing hallucinations, dreams, corporations, ecologies, and other non-material or semi-material entities to be considered objects within OOO. Harman uses this definition of an “object” to question the traditional division between human “subjects” and non-human “objects,” calling it a “shoddy dualism” that “introduces the implausible taxonomy between human thought on one side and everything else in the universe on the other” (56, emphasis in original). In this way, OOO rejects the practice of traditional philosophy to either “undermine” or “overmine” objects as “things-in-themselves.”
                    Undermining is the tendency to search for an underlying reason or force behind all phenomena and has been rooted in western philosophy since the pre-Socratic thinkers, most notably the Greek philosophers Lepucippus and Democritus and their concept of atomism in the 5th century BCE (Pullman 1998). Undermining can trace its lineage to today’s “string theory” as a “theory of everything,” and, as Harman argues, it is the goal of most natural sciences. Overmining is the tendency to value things only for what they do, not what they are. It is rooted in the 17th century “immaterialism” of George Berkeley (1975) and became popularized in post-modern thought, particularly in the social sciences through Michel Foucault (1972; 1979) who saw objects as epiphenomenal to discourse and valid only in how they are used to negotiate power relationships. The relationality of objects and non-human entities is a deeply entrenched tenet of most social theory and, in many ways, is why the “ontological turn” is such radical break from what has come before it.
                    Harman and others that adhere to OOO push back against undermining and overmining by positing that objects have emergent properties. “Emergence” has its own history that will not be discussed here, but in essence describes the phenomena of objects taking on new qualities not found in their individual elements. It follows that other emergent properties will arise when those objects come together (Gregersen 2003). Thus, objects have unique qualities that cannot be reduced by undermining, nor can they be overmined by their influence on other objects.
                    By decentering human subjectivity and placing humans on the same epistemological level as all other objects, OOO adopts a “flat-ontology” (Latour 1996; 2013). Flat-ontology refers to a “flattening” of epistemology that assumes no a prior division between “nature/culture” or “subject/object.” A flat-ontology necessitates situated knowledges that are specific interactions between actors and rejects the “transcendental, all‐seeing and objective mode of knowledge‐production that science has developed for itself” (Nayar 2015). As an example, Annamarie Mol (2002) employs a form of flat-ontology in her “ethnography” of atherosclerosis at a Dutch hospital by drawing attention to the importance of medical imaging, diagnostic machines, and other, more familiar forms of ethnography, such as interviews, during a diagnosis of a patient. For Mol, the doctor and patient are but only a few actors in an assemblage of human and non-human engagements with atherosclerosis which include, but are not limited to, the technologies that measure blood pressure, the patient’s medical records, and the microscopes used to examine plaque in the veins of deceased patients. The specifics of these interactions are tied to the particularities of those actors at that specific hospital, at that specific time. Thus, by adopting a flat-ontology we surrender “objective,” knowledge that exists free from the actors that help produce it. Such contingent knowledges in OOO is considered to be situated.
                    Ultimately, OOO requires us to view “objects” as valid things with qualities that are not epiphenomenal to larger “constructs” of “society,” “culture,” structures,” or “discourses.” Nor can “objects” be reduced to the sum of their parts, as subatomic particles, or as purely phenomenological entities, as nerve impulses. In this way, OOO provides a way for social scientists to think of a world outside of human subjectivity, one populated with a multitude of interacting and self-sufficient objects, many of which humans have nothing to do with. It also allows us to find once traditional “human” qualities in non-human things, such as plants, animals, and the “great outdoors” (Kohn 2013:315), more broadly.
                    OOO in archaeology
                    OOO has taken root in archaeology as the “new materialism,” an un-unified set of approaches to archaeological objects which gives primacy to objects themselves, not what they tell us about humans in the past. In other words, archaeologists who adhere to the new materialism argue against attempts to “move beyond,” “transcend,” or “overcome” artifacts in order to “get at” people (Olsen, et al. 2012). Gavin Lucas (2012), for example, argues that archaeologists do not study “immaterial abstractions,” such as “states, ideologies, chiefdoms, or societies,” but rather the “residue” of “past events” (170). [DGG5] Christopher Witmore (2014:223) describes the difference between the “new materialism” and other forms of archaeology as such:
                    Such definitions stand against the common notion of archaeological practice as the creation of narratives about the past which are constrained by material evidence (cf. Wylie 2002). If archaeology surrenders the claim to developing narratives in order to “embrace… an engagement with things” what exactly do archaeologists contribute to the world that OOO as a philosophy does not already achieve? If it has been established that objects, broadly defined, have agency and need not rely on human subjectivity to validate their existence, what good is it to have archaeologists, many of who are untrained in continental philosophy (including myself), weigh in on this “ontological turn”? Yes, we may provide interesting and very old objects from which we may meditate on their “thingness,” but no significant insight or better understanding of the past will likely come from such work.
                    Frankly, I believe OOO has become popular in archaeology as a way for archaeologists to excuse themselves from making claims about non-western peoples at a time when their authority to make such claims has been thoroughly questioned. “Objects,” and “things” have become “perfect subjects” due to their inability to speak against their (mis)representation. (see Fowles 2016 for a more developed argument on this). We need not turn to “things” when people begin to speak for themselves. As I will argue, theoretical toolkits that allow archaeologists to decenter human subjectivity and to take seriously the agency of non-human entities can already be found in indigenous ontologies.
                    <br></br>
                    <br></br>
                    <b>Indigenous ontologies</b>
                    <br></br>
                    Linda Tuhiwai Smith (2012) first published her polemic book, Decolonizing Methodologies, in 1999, the same year Graham Harman coined the term “object-oriented philosophy.” In her book, Smith brings attention to the generally insidious nature of “research” for indigenous peoples and the lingering effect of “western science” as a tool of colonial power, claiming that, “ [the] collective memory of imperialism has been perpetrated through the ways in which knowledge about indigenous peoples was collected, classified and then represented in various ways back to the West, and then, through the eyes of the west back to those that have been colonized.” She maintains that such research is appropriative by stating, “the west can desire, extract and claim ownership of our ways of knowing, our imagery, the things we create and produce, and then simultaneously reject the people who created and developed those ideas and seek to deny them further opportunities to be creators of their own culture and own nations” (1). I follow Smith in her view that some western research is extractive and self-affirming by highlighting the similarities of OOO and some aspects of indigenous ontologies. I argue that by failing to incorporate indigenous worldviews, the “new materialism” upholds the “validity” of western ways of knowing while simultaneously delegitimizing indigenous philosophies.
                    Objects and non-human entities
                    As archaeologists, we are already familiar with the notion of “situated knowledges.” Our fragmentary data come from specific locations and chronological sequences allowing us to make claims about certain places at certain times but not others. We are right to remain acutely aware of the immobility of our knowledge, and perhaps annoyingly so. While OOO would refer to this “situated knowledge” as being produced when working with excavated materials and the literal archaeological “record” as texts, photographs, and other means of recordation (Hicks 2010; 2016), I am choosing to view “situated knowledge” to include engagements with descendant communities who share a common history tied to place. We may still find debates over “high-theory,” such as OOO thought provoking, but we are better served to apply perspectives of descendent communities in our interpretations rather than esoteric philosophical framings. This extends beyond knowledge of cultural practices or “middle-range” research, but rather, is a call to take indigenous epistemologies seriously and to incorporate such world views in our work. Simply put, citation practices matter. We do not necessarily have to bring Latour, Harman, Harraway, Tsing, or Eduardo Viveros de Castro into our writing when we want to explore the agency of non-human entities or rethink the “nature/culture” divide. Rather, we could start with how descendent communities view such relationships and let them guide our theoretical scaffolding.
                    While this applies to “theory” more broadly, I find OOO and the “new materialism” as being particularly oblivious to indigenous epistemologies. This is especially true in locations of settler-colonialism and the histories of displacement, dispossession, and erasure of indigenous heritage and culture inherent to them. The agency, emergent properties, and power of non-human entities have been well known by many indigenous communities for millennia, and to have archaeologists only now come to this realization through western philosophy is dismissive of these deep histories. Those working in cultural heritage studies have been well aware of this and I find some of their work helpful in drawing connections between OOO and some aspects of indigenous epistemologies.
                    For example, Jon Daehnke (2017) describes how the Chinook Indian Nation of the lower Columbia river view “heritage” as a “web of reciprocity that exists between all things, both human and nonhuman, tangible and intangible,” (5–6) and that “reciprocal responsibilities” join “both human and nonhuman” actors together (11). Deborah Bird Rose (1992; 2004; 2011) has written extensively on how Aboriginal Australians conceptualize human and non-human relationships and the types of reciprocal kinship they have with dingos and other animals. Sally K. May (2010), also working in Australia, explores the lingering trauma of “scientific collecting” in the mid 19th century and details the struggle of some communities still fighting for access to these collections, who they see as being “part of their families.” Chip Colwell (2015; 2009; 2010) has explored the tensions between western and indigenous conceptions of “objects” under museum settings, the former seeing objects as valuable data concerning the past and the latter as living beings with rights and privileges. Catharine Bell and Robert K. Paterson (2009) highlight legal issues when western notions of property are applied to collectively owned objects, landscapes, and other forms of “intangible heritage” belonging to First Nation communities in Canada, showing how western epistemologies are validated through laws which are used to delegitimize indigenous claims to their heritage. These, and many other examples from culture heritage studies, arrive at the main postulates of OOO through their collaborations with indigenous communities. Specifically, objects and non-human life unquestionably have agency for many indigenous peoples. It would, for example, be difficult for the Zuñi to “overmine” or “undermine” one of their “War Gods,” or wooden anthropomorphic statues that are considered living deities (Colwell 2015). Similarly, the agency of non-humans is repeatedly brought up in this literature. For example, Robin Wall Kimmerer (2013), in her book Braiding Sweetgrass, points out that the Potawatomi language has a “grammar of animacy” which affords non-humans “personhood,” and mentions the possibility that lacking such grammar may lead to the “mindless exploitation of land” (58).
                    Ultimately, if we are to take the call for “decolonizing methodologies,” (Kovach 2009) and “native science” (Cajete 2000) seriously, we must begin to employ the epistemological paradigms of indigenous thought into our work. In the context of non-human agency and the ontological validity of “objects,” this means acknowledging the perspectives of descendent communities first and foremost, and then acknowledging Harman, Latour, the other OOO thinkers, and western philosophy for catching up to indigenous world views. What I advocate for here is nothing new. Rather, it is a form of “community based participatory research” (Atalay 2012). There is no need to decry that we are in the midst of an “interpretive dilemma” (Lucas 2012) that “questions archaeology’s underlying metaphysical assumptions” (Alberti 2016) when we want to talk about “that which lies outside the human” (Kohn 2013). We need to first listen to what indigenous communities have to say about these things and to take them at just as seriously as we do the esoteric meanderings of western philosophy.
                    In the second half of this paper, I describe the origins of historical-ecology and its theoretical underpinnings, specifically its relationship to landscape archaeology and practice theory. In doing so, I want to highlight the distinction between a theory and approach. Historical-ecology is first and foremost an approach to archaeology, meaning that it has specified goals and objectives. Specifically, historical-ecology uses history, broadly defined, to understand past ecosystems and then apply this knowledge in the management of contemporary ones. This differs from theory, or what I have lumped together as “ontology” or “epistemology” (see “notes on terminology” in Ch. 1 of Kovach 2009 for a detailed discussion on the difference). I take theory to mean one’s understanding of what is real and how this is determined.
                    With that said, I believe that historical-ecology is an approach that provides a way for archaeologists to talk about non-human agency in a pragmatic way that does not pedestal theory at the expense of indigenous world views. Said differently, we as archaeologists are better off refining our science and developing “middle-range” theories based on actualistic studies and leave forms of “high theory” to communities who will use archaeological data as they wish. Heidegger can wait at home.
            <br></br>
            <b>Defining historical-ecology</b>
            Within the past two decades, historical-ecology has blossomed into a global research agenda that brings together archaeology, ecology, biology, anthropology, ethnohistory, and geography, toward the conservation and restoration of natural and cultural heritage (Crumley 2015; Isendahl 2016; Szabo 2015). However, it lacks a “unified methodology, specialized institutional backgrounds, [or] common publication forms,” (Szabo 2015:998) making specific definition of the approach elusive. Rather, this lack of institutional oversight and unified methodology has led “historical-ecology” to have multiple, generally interchangeable, working definitions. These definitions vary upon the academic background of the researcher, their research questions, and the goals in which they position their work. One broad definition is any, “research concerned with decadal, centennial, and millennial human-environmental interactions, and the consequences that those relationships have in the formation of contemporary landscapes” (Armstrong, et al. 2017:1). This definition is general enough to be applicable to various disciplines but there some overarching trends in how historical-ecology has been defined that are worth discussing further.
            Peter Szabo (2015), in a review of historical-ecology literature published in English, French, Italian, and German within the last sixty years, notes that an “ecological” and “anthropological” definitions of historical-ecology are apparent (1010). “Ecological” definitions tend to view humanity as an outside influence acting upon ecosystems while “anthropological” ones examine the ecological implications of human action. For example, Beller et al. (2017) provide a good “ecological” definition of historical-ecology published in a botany journal, as “the study of nature over time[DGG21] … with a focus on human-environment interactions” (645). For Crumley et al. (2017), historical-ecology “traces the complex relationship between our species and Earth, examined over the long term” (1). The difference is subtle but important as Szabo shows that “anthropological” writers will often cite “ecological” publications more often than vice-versa. Szabo also calls attention to the different ways “historical-ecology,” developed in North America and Europe, with North American researchers favoring an “anthropological” perspective and those in Europe favoring an “ecological” one. Here, I focus on the origin of “anthropological” perspectives in North America.
            The works of historian William Cronon, are some of the most iconic and earliest forms of historical-ecology research in North America. In his book Changes in the Land: Indians, Colonists, and the Ecology of New England, Cronon, (1983) used both archival and ecological data to show how European colonizers dramatically alerted the New England landscape, linking contemporary environmental and geographic conditions to a specific historical moment. Similarly, in his polemic essay “The Trouble with Wilderness: Or Getting Back to the Wrong Nature,” (1995) Cronon, deconstructed the common understanding of “wilderness” and showed how natural spaces are “constructed” through practices, discourse, and law. Cronon’s work was one of the first popular and widely read attempts to problematize the division between “nature,” and “culture,” from a historical perspective and his work is still foundational for environmentally focused social sciences. Outside of history, historical-ecology gained notoriety from two edited volumes. William Balee(1998), editor of Advances in Historical Ecology, brought attention to the influence of human intervention and historical events to the study of ethnobotany. Carole L. Crumley (1994), and the contributors to the seminal volume Historical Ecology, brought questions of historical processes and environmental change to the practice of archaeology under the label of “historical-ecology,” although archaeologists have long studied human-environmental relationships, albeit under different names (cf. Dincauze 2000). Historical Ecology remains an important source material and continues to be referred to by archaeologists and ecologists alike (Szabo 2015:1011).
            While the contributions of Cronon, Crumley, and Balée laid the foundation of a multi-disciplinary approach to the study of human-ecodynamics for North American researchers, historical-ecology has more recently undergone a transformation from being a “viewpoint,” (Balee 1998:14) to being a research “program,” with specified goals and objectives (Crumley 2015; 2017). In a survey of over 300 self-proclaimed “historical-ecologists,” for example, Armstrong et al. (2017) identified three overarching postulates by which these researchers frame their work. First, there was a general agreement that historical-ecology was a “fundamentally applied research program,” and that research should be conducted with the conservation and restoration of natural and cultural heritage in mind. Secondly, historical-ecology should be focused “on avoiding, mitigating, and reversing [human caused] adverse ecological effects.” Lastly, they believed that historical-ecology should strive to be a truly “transdisciplinary research science, which erodes scientific boundaries between the cultural and natural” (2).
            Thus, historical-ecology is more than a theoretical approach but rather a pragmatic intervention in current conservation and environmental policy regimes. Importantly, the main supporters of such pragmatic research are not universities and other academic institutions whose disciplinary “siloing” complicates the transdisciplinary approaches of historical-ecology. Rather, NGOs, environmental advocacy groups, land trusts, indigenous communities, and other organizations have been the primary drivers of historical-ecology as their project driven and fluid infrastructure has allowed for such interdisciplinary and open-ended approaches to flourish (Crumley 2015).
            With its general historical trajectory detailed, we may now turn our attention to historical-ecology’s theoretical underpinnings and archaeology’s contribution to its larger goals. Specifically, the longue durée, the “landscape,” and practice theory, are crucial for setting the scale and tempo of historical-ecology’s focus.
            Temporalizing ecology
            The longue durée, or simply “long duration,” refers to structures of social persistence and change that occur over very long periods of time and which only become observable in retrospect via multiple forms of data. It was coined in 1949 by Braudel (1980) of the French Annales school of historical writing. Growing out of a mistrust for “events” based histories and in a world weary of dramatic power shifts in the aftermath of World War II (Harris 2004:161), the longue duree emphasized gradual change and matched the Annales school’s goal of developing a “total history” that extended beyond the myopic emphasis on the succession of royalty, outcomes of conquests, or other types high politics that are the focus of most historiography (Harsgor 1978). The longue durée first found favor in archaeology during 1980–1990s by archaeologists emboldened by the calls for multivocality and critical rethinking of the archaeological record during the post-processualist movement. For some, the longue durée was seen as a way to historicize North American hunter-gathers in novel ways and break free from an emphasis on cultural “systems” or “behavior” (e.g. Bird 2006; Flannery 1968). For example, Ames (1991), utilized the longue durée to argue against uncritical applications of ethnographic research in his reanalysis of the origins of social complexity along the Northwest Coast. Rather than projecting what was ethnographically observed into the past, Ames suggested that the origins of “complexity” have a deep history, developing at different times in different places and is the product of truly historical processes, rather than the predetermined outcome of ecology or population size.
            Within historical-ecology, the longue durée is used to set the temporal frame of research, such that the relationship between humans and non-human entities is to be examined through long term gradual changes in the archaeological record. The longue durée is a critical component to making historical-ecology a pragmatic research program as understanding long term human-non-human relationships allows us to set ecosystem baselines that extend deeper in the past than historic records permit. Such baselines have implications for contemporary conservation efforts, including the reintroduction of species to their once historical ranges (Jachowski 2016; Klein 2016).
            While the longue durée provides the temporal frame for historical-ecology, the “landscape,” and practice theory help populate that time with actors that do things. As I will show below, an anthropological approach to landscapes links everyday patterns of human and non-human entities to a place and allows us to explore how the longue durée is created via practices (cf. Bourdieu).
            Practices in the land
            The works of Ingold are perhaps the most influential writings on “landscapes” for archaeologists and his concepts are employed regularly by historical-ecologists. Specifically, his concept of “dwelling” has important implications for historical-ecology. In his famous essay “The Temporality of Landscape,” Ingold (1993) links practices to geography in such a way that “pattern[s] of activities” are “‘collapsed’ into an array of features [on the land]” (162). The landscape begins to reflect these practices, entering into a complex reciprocal relationship with people and non-human entities wherein individuals come to embody the landscape while simultaneously altering it. He called this dialectical relationship “dwelling” in the land (156). Following Ingold, Balée (1998) claims that historical ecology, for all intents and purposes, is synonymous with “dialectical ecology” (13) as it attempts to make sense of how day-to-day practices of people and non-human entities result in often subtle changes to landscapes and how these changes loop back to further influence human and non-human practices.
            An example of the co-construction of landscapes can be found in Lovis and Whallon’s (2016), introduction to Marking the Land: Hunter Gather Creation of Meaning in Their Environment. In it, they detail the possible ways in which practices of mobility, foraging, and hunting imbue landscapes with social meaning, either consciously or unconsciously. They note how “redundant behaviors,” such as simply walking to and from various seasonal camps, can result in “visible trackways, paths, trails, and traces” (1), and how these can further promote certain practices. Likewise, they note how hunter-gathers may have helped in ecological “niche construction,” through the “unintentional alterations of soils,” and suggest that oral histories and folklore may serve as mnemonic devices that communicate complex information regarding the landscape over generations and across space (3–5) . Importantly, non-human actors, such as wild game, are also capable of making such changes to a landscape.
            Historical-ecologists are also concerned with the origin, maintenance, and change of active management practices toward the landscape. Lightfoot et al. (2013), for example, examine anthropogenic burning practices of native peoples on the California coast and argue for reintroducing similar burns in contemporary fire management regimes. McMillan and McKechnie (2015) show how different culturally informed hunting practices of Wakashan and Nuu-chan-nulth language groups on Vancouver Island, BC resulted in stark differences in resource exploitation patterns. In this example, social differences of “proper” places to forage led to a heterogeneous impact on the landscape. This, in turn, has implications for contemporary resource management strategies as baseline population estimates are often modeled after historical, post contact records, thus obfuscating the differential impact Native peoples have had on wildlife populations prior to European encroachment (Jachowski 2016).
            At its most fundamental level then, historical ecology is concerned with the long-term effects of human and non-human practices on the landscape. Practices, as opposed to behavior (i.e. adaptation), emphasizes motivated action in the sense that actors with agency act based on historical and culturally specific contexts with intended outcomes that may or may not be realized (Leroi-Gourhan 1964 (1993)); Bourdieu, 1977 (1972)). We may extend this definition of “practices” to animals and other non-human entities. Importantly, as Crumley (1994) suggests, “both conscious and unconscious,” practices can “change the face of the earth” (6). Thus, the notion of “dwelling” lies at this nexus of practice and landscape, linking the everyday with the longue durée.
            With its attention to the longue durée, landscape, and practices, historical-ecology develops a tool-kit from which to examine the relationship between humans and non-humans in a way that develops knowledge about a particular place and does away with grand narratives of ecological collapse or “garden of Eden” largesse that often circulate in popular culture when discussing pre-contact indigenous life. Furthermore, it does not question the ontological “validity” of objects and non-human life, but rather takes these as a given and moves on to bigger issues such as natural resource conservation, land use rights, and indigenous sovereignty.
            Ultimately, I see archaeological practice as a tool to recover and preserve data about the past and historical-ecology as an excellent approach that takes this data and makes it valuable to multiple publics. We do not have to choose between “community based participatory research,” critical heritage studies, or environmentally focused archaeology. We are more than capable doing all these things simultaneously. We cannot, however, be bogged down too long by philosophical discussions in “high-theory” regarding the role of non-humans. Yes, they have agency and we should recognize indigenous peoples for recognizing this fact first. Let us now mobilize that knowledge and do something.
            Works Cited
            Alberti, Benjamin
            2016 Archaeologies of Ontology. Annual Review of Anthropology 45(1):163–179.
            Ames, Ken
            1991 The archaeology of the longue durée: temporal and spatial scale in the evolution of social complexity on the southern Northwest Coast. Antiquity 65(249):935–945.
            Armstrong, C. G., et al.
            2017 Anthropological contributions to historical ecology: 50 questions, infinite prospects. Plos One 12(2).
            Atalay, Sonya
            2012 Community-based archaeology : research with, by, and for indigenous and local communities. Berkeley: University of California Press.
            Balee, William
            1998 Historical Ecology: Premises and Postulates. In Advances in Historical Ecology. W. Balee, ed. Pp. 13–29. New York: Columbia University Press.
            Bell, Catherine E., and Robert K. Paterson
            2009 Protection of First Nations cultural heritage : laws, policy, and reform. Vancouver: UBC Press.
            Beller, E., et al.
            2017 Toward principles of historical ecology. American Journal of Botany 104(5):645–648.
            Berkeley, George
            1975 Philosophical works : including the works on vision. London, Totowa, N.J.: Dent; Rowman and Littlefield.
            Bessire, Lucas, and David Bond
            2014 Ontological anthropology and the deferral of critique. American Ethnologist 41(3):440–456.
            Bird, Douglas W. and James F. O’Connell
            2006 Behavioral Ecology and Archaeology. Journal of Archaeological Research 14:143–188.
            Boyd, Brian
            2017 Archaeology and Human-Animal Relations: Thinking Through Anthropocentrism. Annual Review of Anthropology 46:299–316.
            Braudel, Fernand
            1980 On History. Chicago: University of Chicago Press.
            Cajete, Gregory
            2000 Native Science: Natural Laws of Hnterdependence. Santa Fe, N.M.: Clear Light Publishers.
            Colwell, Chip
            2015 Curating secrets repatriation,knowledge flows, and museum power structures. Current Anthropology 56:S263-S275.
            __ 2009 Inheriting the past : the making of Arthur C. Parker and indigenous archaeology. Tucson: University of Arizona Press.
            —
            2010 Living histories : Native Americans and Southwestern archaeology. Lanham, Md.: AltaMira Press.
            Cronon, William
            1983 Changes in the Land: Indians, Colonists, and the Ecology of New England. New York: Hill and Wang.
            —
            1995 The trouble with wilderness; or, getting back to the wrong nature. In Uncommon Ground: Rethinking the Human Place in Nature. W. Cronon, ed. Pp. 69–90. New York: W.W. Norton & Co.
            Crumley, C. L.
            2015 New paths into the Anthropocence: Applying historical ecologies to the human future. In The Oxford Handbook of Histroical Ecology and Applied Archaeology. C.I.a.D. Stump, ed. Oxford Oxford University Press.
            Crumley, Carole L.
            1994 Historical ecology : cultural knowledge and changing landscapes. Santa Fe, N.M. Seattle: School of American Research Press ; Distributed by the University of Washington Press.
            Crumley, Carole L., Tommy Lennartsson, and Anna Westin
            2017 Issues and concepts in historical ecology : the past and future of landscapes and regions. Cambridge, United Kingdom ; New York, NY: Cambridge University Press.
            Daehnke, Jon Darin
            2017 Chinook resilience : heritage and cultural revitalization on the lower Columbia River. Seattle: University of Washington Press.
            de Castro, Eduardo Viveiros
            2015 Who is afraid of the ontological wolf? Some comments on an ongoing anthropological debate. The Cambridge Journal of Anthropology 33(1)PAGES.
            Dincauze, Dena Ferran
            2000 Environmental archaeology : principles and practice. Cambridge, UK, New York: Cambridge University Press.
            Flannery, Kent V.
            1968 Archaeological systems theory and early Mesoamerican prehistory. In Anthropological Archaeology of the Americas. B.J. Meggers, ed. Washington D.C.: Anthropological Society of Washington.
            Foucault, Michel
            1972 The archaeology of knowledge. London,: Tavistock Publications.
            —
            1979 Discipline and punish : the birth of the prison. New York: Vintage Books.
            Fowles, S.
            2016 The perfect subject (postcolonial object studies). Journal of Material Culture 21(1):9–27.
            Giaccardi, E., et al.
            2016 Thing ethnography: Doing design research with non-humans. Dis 2016: Proceedings of the 2016 Acm Conference on Designing Interactive Systems:377–387.
            Ginn, Franklin
            2014 Jakob von Uexküll beyond bubbles: On Umwelt and Bbiophilosophy. Science as Culture 23(1):129–134.
            Gregersen, Niels Henrik
            2003 From complexity to life : on the emergence of life and meaning. Oxford ; New York: Oxford University Press.
            Haraway, Donna J.
            2008 When species meet. Minneapolis: University of Minnesota Press.
            —
            2016 Staying with the trouble : making kin in the Chthulucene. Durham: Duke University Press.
            Harman, Graham
            1999 Tool-Being: Elements in a Theory of Objects Philosophy, DePaul University
            —
            2010 Towards Speculative Realism: Essays and Lectures. London: Zero Books.
            —
            2011 Quentin Meillassoux : philosophy in the making. Edinburgh: Edinburgh University Press.
            —
            2018a Object-Oriented Ontology: A new theory of everything. London: Pelican Books.
            —
            2018b Speculative realism : an introduction. Medford, MA: Polity.
            Harris, Olivia
            2004 Braudel: Historical Time and the Horror of Discontinuity. History Workshop Journal 57:161–174.
            Harsgor, Michael
            1978 Total History: The Annales School. Journal of Contemporary History 13(1):1–13.
            Hartigan, John
            2015 Aesop’s Anthropology: A Multispecies Approach Minneapolis University of Minnesota Press.
            —
            2017 Care of the species : races of corn and the science of plant biodiversity. Minneapolis: University of Minnesota Press.
            Hayles, Katherine
            1999 How we became posthuman : virtual bodies in cybernetics, literature, and informatics. Chicago, Ill.: University of Chicago Press.
            Heidegger, Martin, Joan Stambaugh, and Dennis J. Schmidt
            2010 Being and time. Albany: State University of New York Press.
            Hicks, Dan
            2010 The material-cultural turn: event and effect. In The Oxford Handbook of Material Culture Studies. D.H.a.M.C. Beaudry, ed. Pp. 25–98. Oxford: Oxford University Press.
            —
            2016 The Temporality of Landscape. Norwegian Archaeological Review 49(1):5–22.
            Hodder, Ian
            2012 Entangled : an archaeology of the relationships between humans and things. Malden, MA: Wiley-Blackwell.
            Ingold, Tim
            1993 The temporality of landscape. World Archaeology 25(2):152–174.
            Isendahl, Christian
            2016 Historical ecology coming of age. Reviews in Anthropology 45(3):127–147.
            Jachowski, David S. with Joshua J. Millspaugh, Paul L. Angermeier, and Rob Slotow, editors., ed. 2016 Reintroduction of Fish and Wildlife Populations. Berkeley: University of California Press.
            Kimmerer, Robin Wall
            2013 Braiding sweetgrass. Minneapolis, Minnesota: Milkweed Editions.
            Klein, Emily S. and Ruth H. Thurstan
            2016 Acknowledging long-term ecological change: The problem of shifting paselines. In Perspectives on Oceans Past. B.P. K. Scwerdtner Manez, ed. Pp. 11–29: Springer Science+Business Media Dordrecht.
            Kohn, E.
            2015 Anthropology of ontologies. Annual Review of Anthropology, Vol 44 44:311–327.
            Kohn, E., and S. M. Cruzada
            2017 How Dogs Dream … Ten Years Later. Aibr-Revista De Antropologia Iberoamericana 12(3):273–311.
            Kohn, Eduardo
            2013 How forests think : toward an anthropology beyond the human. Berkeley: University of California Press.
            Kovach, Margaret
            2009 Indigenous methodologies : characteristics, conversations and contexts. Toronto ; Buffalo: University of Toronto Press.
            Latour, Bruno
            1993 We have never been modern. Cambridge, Mass.: Harvard University Press.
            —
            1996 On actor-network theory — A few clarifications. Soziale Welt-Zeitschrift Fur Sozialwissenschaftliche Forschung Und Praxis 47(4):369-&.
            —
            2013 An inquiry into modes of existence : an anthropology of the moderns. Cambridge, Massachusetts: Harvard University Press.
            Latour, Bruno, and Catherine Porter
            2017 Facing Gaia : eight lectures on the new climatic regime. Cambridge, UK ; Medford, MA: Polity.
            Leroi-Gourhan, Andre
            1964 (1993) Gesture and speech. In Gesture and Speech. An OCTOBER Book of the MIT Press. Cambridge, MA: The MIT Press.
            Lightfoot, K.G. with Rob Cuthrell, Cristie M. Boone, Roger Byrne, Andreas S. Chaves et al.
            2013 Anthropogenic burning on the Central California coast in Late Holocence and early historical times: Findings, implications, and future directions. California Archaeology 5(2):371–390.
            Lovis, William A. and Roberth Whallon
            2016 The creation of landscape meaning by mobile hunter-gatherers In Marking the Land: Hunter Gather Creataion of Meaning in Their Environment. e. William A. Lovis and Robert Whallon, ed. Pp. 1–9. New York: Routledge
            Lucas, Gavin
            2005 The Archaeology of Time. London;New York: Routledge.
            —
            2012 Understanding the Archaeological Record. Cambridge: Cambridge University Press.
            May, Sally K.
            2010 Collecting cultures : myth, politics, and collaboration in the 1948 Arnhem Land Expedition. Lanham, Md.: AltaMira Press.
            McMillan, Alan D., and I. McKechnie
            2015 Investigating indigenous adaptations to British Columbia’s Exposed Outer Coast BC Studies 187:3–20.
            Mol, Annemarie
            2002 The body multiple : ontology in medical practice. Durham: Duke University Press.
            Nayar, Pramod K.
            2015 The postcolonial studies dictionary. Chichester, West Sussex, UK ; Malden, MA,: Wiley.
            Olsen, Bjornar, et al.
            2012 Archaeology: the Discipline of Things. Berkeley: University of California Press.
            Overton, N. J.
            2016 More than skin seep: Reconsidering isolated remains of ‘fur-bearing species’ in the British and European Mesolithic. Cambridge Archaeological Journal 26(4):560–577.
            Overton, N. J., and Y. Hamilakis
            2013 A manifesto for a social zooarchaeology. Swans and other beings in the Mesolithic. Archaeological Dialogues 20(2):111-+.
            Pullman, Bernard
            1998 The atom in the history of human thought. New York: Oxford University Press.
            Rose, Deborah Bird
            1992 Dingo makes us human : life and land in an aboriginal Australian culture. Cambridge ; New York: Cambridge University Press.
            —
            2004 Reports from a wild country : ethics for decolonisation. Sydney, NSW: UNSW Press.
            —
            2011 Wild dog dreaming : love and extinction. Charlottesville, VA: University of Virginia Press.
            Szabo, P.
            2015 Historical ecology: past, present and future. Biological Reviews 90(4):997–1014.
            Tsing, Anna Lowenhaupt
            2005 Friction : an ethnography of global connection. Princeton, N.J.: Princeton University Press.
            —
            2015 The mushroom at the end of the world : on the possibility of life in capitalist ruins. Princeton: Princeton University Press.
            —
            2017 Arts of living on a damaged planet. Minneapolis: University of Minnesota Press.
            Witmore, Christopher
            2014 Archaeology and the New Materialisms. Journal of Contemporary Archaeology 1(2):203–246.
            Wylie, Alison
            2002 Thinking from things : essays in the philosophy of archaeology. Berkeley: University of California Press.
            1
            
            
            </p>
         </div>
        </div>
    )
}

export default Articles;